apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example-app-prod
  template:
    metadata:
      labels:
        app: example-app-prod
    spec:
      containers:
        - image: artpasut/argo-app:1.0.0
          name: example-app-prod
          ports:
            - containerPort: 80
